### ISSUE TITLE
git submodule handling during checkout is pulling wrong commit id

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autobuild#46]
During git checkout submodules are set to their latest commit id which might be more advanced than the one specified by their parent git.

**Reason:**
autobuild is using the recursive option to checkout submodules. In case the master branch is checkout  this is also applied to its submoduls which gives an undesired version mix.

**Workaround:**
git reset --hard
git submodule update

**Possible Fix**
use git submodule init and git submodule update instead of recursive checkout.

**Comment by doudou** [comment]
I've just had a hard look at the codepath and git submodules documentation.

I didn't see anything in the `git submodule` documentation that would explain this behavior.

However, in autobuild ... From what I gather this would happen in the case where the local branch is not master. It would happen because [the #update method](https://github.com/rock-core/autobuild/blob/master/lib/autobuild/import/git.rb#L984) would return before `submodule update --init` gets run.

Is this your case ?

**Comment by D-Alex** [comment]
You are right the repo those submodules get set to the latest commit id has the following settings:

 - external/grpc:
        type: git
        github: krakenrobotik/grpc
        branch: install_fix 
        with_submodules: true

**Comment by doudou** [comment]
OK then ... I know what to do...

**Comment by doudou** [comment]
Should be fixed by #47.

Do you have a dev install of autoproj/autobuild ? I could do a prerelease for you to test otherwise.
