### ISSUE TITLE
manage C[XX]FLAGS environment variable to setup include dirs

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autobuild#50]
This would ease integration of cmake/autotools packages that do not provide a pkg-config file, specially with autoproj's "separate prefixes" option. The idea is to patch `Autobuild::Environment#add_prefix` to append `-I#{new_prefix}` and `-L#{new_prefix}` to `CFLAGS`, `CXXFLAGS` and `LDFLAGS` if the new prefix contains an `include/` and/or `lib/` folder  (filtering out possible dupes)

**Comment by doudou** [comment]
Interestingly, the issue was specifically mentioning the separate prefixes option.

For the record, what I think would be an 'autobuild-autoproj' solution to deal with these packages would be to give an API on cmake/autotools packages to deal with these flags *for specific dependencies*, e.g.

~~~
cmake_package 'my/package' do |pkg|
   pkg.guess_compilation_flags 'some/dependency'
end
~~~

if some weird things are needed, one could do

~~~
cmake_package 'my/package' do |pkg|
   pkg.guess_compilation_flags 'some/dependency' do |guess|
       # Fine-tune the guesses
   end
end
~~~

Unlike #51, it ensures that the flags are package-local instead of ending up globally, generally solving the whole "a package does not provide anything to guess the flags"

For what it's worth, this use-case is even narrower: it would be for packages where neither the package nor its dependency use proper dependency-tracking methods. A cmake package that depends on another "bad" package should have its own dependency-discovery method (which can rely on giving the package's prefix, but that's about it).

**Comment by g-arjones** [comment]
Yeah, well.. By "guess", heuristics come to mind and personally, I have a tendency to dislike that. Besides, I don't think compilation "flags", in general, should be guessed by either autoproj nor autobuild. The particular thing I was trying to set was search paths and that IMO, should be global (which is consistent with all search paths that the autoproj-autobuild duo set). The reason I would use a compilation flag for that is because compilers do not provide a specific environment variable just for search paths but the effect is the same.

The problem I have with what you are suggesting is having to repeat that same thing for all packages that depend on third-party packages that do not provide .pc files (which is quite often). The fact that this would have to be done in the package set makes things even worse (one would have to repeat the same in different package sets). A possible middle ground would be making "guessing" the default for all CMake/autotools dependencies. Thoughts?

**Comment by g-arjones** [comment]
> Yet, you actually assume that autoproj should globally guess what are the good flags

For these search paths (prefixes, /usr on a system level and Autoproj.prefix on workspace level), I don't see that as a guess but as "complying with common behavior" (both autoproj/autobuild and compiler's). Compilers do have, by default, common global search paths and autoproj has quite a few global search paths as well.

> What I was proposing is some kind of a middle ground

I get that. I think we just have different use cases... Right now, I use autoproj/autobuild across several different projects, robotics and non-robotics, professional and otherwise with quite a few unrelated package sets. Anything that has to be done repeatedly for several packages in different package sets is counter productive for me. Still, your solution is a fair one and would probably fit your use case but, as soon as you start using these tools more broadly you will see that it doesn't help that much.

All I am saying is that I would rather do `Autoproj.env.set 'CFLAGS', "-I#{Autoproj.prefix}/include"` in an init script than enabling a "guessing" mode in multiple packages just to make the compiler look for headers in a path that should be the default within the autoproj workflow just like /usr/include is on a system level.

**Comment by doudou** [comment]
> just to make the compiler look for headers in a path that should be the default within the autoproj workflow just like /usr/include is on a system level.

Here's the thing: blindly adding every prefix to CXXFLAGS/LDFLAGS and whatnot is not the default, and not an accepted practice. There are no build system that require you to set up these kind of flags, instead relying on the accepted dependency discovery systems.

Autoproj is following this best practice, in big part not because "it fits my use-case", but because I dont' want to have to figure out what non-standard things Autoproj does once I want to build a package without Autoproj. I'd rather stay with the accepted practice, that is relying on the underlying build systems to do the discovery the packages require. Autoproj is not catkin, the goal is to still ensure that the packages build fine without autoproj. Setting PKG_CONFIG_PATH, CMAKE_PREFIX and RUBYLIB *are* accepted practices. This is how one does set up in a pkg-config system, CMake system and Ruby packages.

The goal is not to automagically help you build whatever you want. If you have something that does not follow the best practices, then it could provide you with some help but this "providing some help" should end up making what's happening explicit.

What's weird to me is that you're fine with globally setting flags that should essentially be set on a per-package basis, but you resist having helpers on the package classes that would do exactly the same in a more local (a.k.a. controlled) way.

**Comment by g-arjones** [comment]
> Setting PKG_CONFIG_PATH, CMAKE_PREFIX and RUBYLIB are accepted practices

What makes ruby's `require`'s search paths different from i.e gcc's `#include`'s search paths? Why is it acceptable to add every prefix to the search paths you mention and not acceptable to do the same with gcc's include search paths?

> but you resist having helpers on the package classes

I am not resisting it, I just think I wouldn't use them because I am not willing to do that for every package in every package set that I have given that I can achieve the exact same result with one line of code and no side effects. I use autoproj because it makes my life easier, what you are suggesting does not.

**Comment by doudou** [comment]
> Why is it acceptable to add every prefix to the search paths you mention and not acceptable to do the same with gcc's include search paths?

Because it is how everybody else is doing it for RUBYLIB, and not how everybody else is doing it for the C++ compiler flags. "Accepted practice".

You might want to fight everybody else on this, but I don't.
