### ISSUE TITLE
Default remote branch targeting master

### ISSUE THREAD

**Issue by ivan1993br** [rock-core/autobuild#92]
## Problem

When cloning with non defined branch the operation points to the `master` branch, instead of the default one on git. This was not a problem before as most of the packages had the `master` as default, however today, git is changing to `main` as discussed [here](https://github.com/github/renaming). The command issued on log with clonning is the following:

```bash
git --git-dir ${PATH}.git fetch git@github.com:${GIT_REPO}.git refs/heads/master
```

## Analysis 
As the sources are loaded, the `remote_branch` member is loaded with the following values, as can be seen [here](https://github.com/rock-core/autobuild/blob/1f55666d28944603b257c6969c55c814aae8a686/lib/autobuild/import/git.rb#L1214)
```ruby
remote_branch =
                options[:remote_branch] || options[:branch] ||
                self.remote_branch || 'master'
```
And the clone follows this ref.

## Proposition
When there is no branch specified, do not specify remote_branch as well (maybe using an empty string?)

What you guys think, am I missing some potential problem?

**Comment by doudou** [comment]
We'll need to handle this case specially everywhere. Plus, we rather obviously would like to have local_branch follow the name of the default remote branch as well.

I believe we would be able handle the remote_branch == nil case specially at cloning time, that is do a plain clone, and then save the resulting branch in a file in the `.autobuild` folder (which is already used for patching). In all other cases, read that file to determine what 'master' is. If the file gets deleted, use the current HEAD to re-create it (which would basically be what happens after cloning)

**Comment by g-arjones** [comment]
I don't understand the need for the file "cache" since git already does that for us. If the goal is to prevent having to shell-out to git maybe we could read `.git/refs/remote/#{@remote_name}/HEAD` ourselves instead. Also, during checkout/update we should probably always query the remote since that can change and break things locally (`git ls-remote --symref #{@remote_name} HEAD`).

Then, there are packages that have been created locally. There's no such thing as a "default branch" for those so we will need some kind of a fallback mechanism until something is pushed to the remote and we can fetch the HEAD

**Comment by doudou** [comment]
Agreed. I didn't think about that ...

I guess the most robust would be:
- if refs/remotes/$NAME/HEAD exists, use that (or, rather, shell out to resolve the link)
- if not, use `ls-remote`
- use `ls-remote` in all cases that hit the remote server (checkout/update), as suggested by @g-arjones
